### ISSUE TITLE
Amélioration sur l'installation des applications

### ISSUE THREAD

**Issue by bnoufel** [nicolinuxfr/macOS-post-installation#2]
Bonjour,

Déjà super article et script ^^

Je peux proposer une petite amélioration sur l'installation des App pour simplifier la vie :)

C'est par exemple de mettre les noms des apps dans un fichier .txt (un par ligne)

et ensuite faire une boucle for dessus (pensez à sécuriser avec des anti-slash pour les espaces)

du coup ça passera sur chacun des apps :)

Je peux contribuer pour ça si besoin

**Comment by nicolinuxfr** [comment]
Bonjour

Merci pour les compliments ! :-)

C'est vrai que ce serait sans doute plus logique ainsi, mais j'ai choisi cette méthode plus simple et plus pédagogique. 

Cela dit, peut-être que cela aurait plus de sens ainsi, je ne sais pas…

**Comment by bnoufel** [comment]
Cela peut-être pratique si on a beaucoup d'app à installer on lance le script comme ça on part au boulot ou autre, on rentre et c'est fini.

Ou alors mettre un prompt 

Installation automatisé ou manuelle :)

**Comment by nicolinuxfr** [comment]
Le script fonctionne de la même manière, une fois lancé, il se débrouille tout seul.

L’avantage de mon approche, je trouve, c’est aussi d’organiser les apps par catégorie. C’est plus facile de s’y retrouver après…
