### ISSUE TITLE
Makefile

### ISSUE THREAD

**Issue by SebastienElet** [nicolinuxfr/macOS-post-installation#3]
Pourquoi ne pas faire un makefile ?

Make permet automatiquement de déclarer les dépendances et permet d'être idempotent (ne rien faire si le fichier existe déjà).

J'utilise avec succès depuis quelques années déjà : https://github.com/SebastienElet/dotfiles/blob/refactor/minimal-setup/Makefile

**Comment by nicolinuxfr** [comment]
Pourquoi pas, mais pourquoi ?

Le script fonctionne assez bien en l'état si on l'applique une deuxième fois. Et le fonctionnement d'un makefile est totalement différent.

En tout cas, c'est une vraie question. Pourquoi est-ce que ce serait mieux ?

**Comment by SebastienElet** [comment]
C'est mieux pour les notions de dépendances, tu peux spécifier qu'une app à besoin de brew/mas/etc... et faire les installations dans le bon ordre.

Et make lance des commandes shell (ou des scripts) donc c'est plus flexible à mon idée.

Après la solution qui claque c'est d'utiliser puppet/ansible

En tout cas merci du partage, c'est top d'avoir des setups mac

**Comment by nicolinuxfr** [comment]
> Après la solution qui claque c'est d'utiliser puppet/ansible

Oula, peut-être, mais moi ça me semble bien trop « *overkill* » pour mes besoins.

Je pense que certains voudront aller beaucoup plus loin, mais pour moi, ces petits scripts me conviennent. 

Merci pour la suggestion en tout cas ! :-)
