### ISSUE TITLE
Mot de passe lisible

### ISSUE THREAD

**Issue by knokknok** [nicolinuxfr/macOS-post-installation#4]
remplacer
read PASSWORD
par
read -s PASSWORD
?

**Comment by nicolinuxfr** [comment]
Bien vu, ça ne me gênait pas trop, mais autant faire ça bien ! 👍 

Corrigé avec https://github.com/nicolinuxfr/macOS-post-installation/commit/60b4a794629562ea02b6f7c185d4578d126013fb
